HARDN_STATUS "info" "Applying safe Lynis score improvements..."

# Set secure permissions on /tmp and /var/tmp
chmod 1777 /tmp
if [[ -d /var/tmp ]]; then
	chmod 1777 /var/tmp
fi

# Secure log file permissions (safe default)
find /var/log -type f -exec chmod 640 {} \; 2>/dev/null || true
find /var/log -type d -exec chmod 750 {} \; 2>/dev/null || true

# SSH hardening with safe login defaults
local ssh_config="/etc/ssh/sshd_config"
if [[ -f "$ssh_config" ]]; then
	HARDN_STATUS "info" "Enhancing SSH configuration for better Lynis scores..."
	cp "$ssh_config" "${ssh_config}.bak.hardn" 2>/dev/null || true

	declare -A ssh_settings=(
		["ClientAliveInterval"]="300"
		["ClientAliveCountMax"]="0"
		["MaxStartups"]="10:30:60"
		["LoginGraceTime"]="60"
		["MaxSessions"]="4"
		["PermitRootLogin"]="prohibit-password"
		["PasswordAuthentication"]="yes"
		["X11Forwarding"]="no"
		["UsePAM"]="yes"
		["Protocol"]="2"
	)

	for key in "${!ssh_settings[@]}"; do
		val="${ssh_settings[$key]}"
		if grep -qE "^#*\s*${key}\b" "$ssh_config"; then
			sed -i "s/^#*\s*${key}.*/${key} ${val}/" "$ssh_config"
		else
			echo "${key} ${val}" >> "$ssh_config"
		fi
	done

	systemctl reload ssh 2>/dev/null || true
fi

# Kernel parameter improvements
HARDN_STATUS "info" "Applying additional kernel parameters for Lynis score improvement..."
local sysctl_lynis="/etc/sysctl.d/99-lynis-hardening.conf"
cat > "$sysctl_lynis" << 'EOF'
# Additional kernel parameters for Lynis score improvement
# Generated by HARDN-XDR

# Network security enhancements
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0
net.ipv6.conf.all.use_tempaddr = 2
net.ipv6.conf.default.use_tempaddr = 2
net.ipv4.tcp_syncookies = 1

# Additional memory protection
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
kernel.unprivileged_bpf_disabled = 1
net.core.bpf_jit_harden = 2

# Process restrictions
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
fs.suid_dumpable = 0
EOF

sysctl -p "$sysctl_lynis" >/dev/null 2>&1 || true

# PAM configuration improvements
HARDN_STATUS "info" "Enhancing PAM configuration for Lynis scores..."
local pam_login="/etc/pam.d/login"
if [[ -f "$pam_login" ]] && ! grep -q "pam_limits.so" "$pam_login"; then
	echo "session required pam_limits.so" >> "$pam_login"
fi

# Limits hardening
if ! grep -q '\* hard core 0' /etc/security/limits.conf 2>/dev/null; then
	echo '* hard core 0' >> /etc/security/limits.conf
fi

# File permission hardening
chmod 644 /etc/crontab 2>/dev/null || true
chmod -R 644 /etc/cron.d/* 2>/dev/null || true
chmod -R 755 /etc/cron.daily /etc/cron.hourly /etc/cron.monthly /etc/cron.weekly 2>/dev/null || true

chmod 644 /etc/passwd 2>/dev/null || true
chmod 640 /etc/shadow 2>/dev/null || true
chmod 644 /etc/group 2>/dev/null || true
chmod 640 /etc/gshadow 2>/dev/null || true

# Remove world-writable permissions from .conf files only
HARDN_STATUS "info" "Removing world-writable permissions from system config files..."
find /etc -type f -name "*.conf" -perm -002 -exec chmod o-w {} \; 2>/dev/null || true

# Set umask
if ! grep -q "umask 027" /etc/profile; then
	echo "umask 027" >> /etc/profile
fi

# Set login banners (safe overwrite)
echo 'Unauthorized access is prohibited.' > /etc/issue
echo 'Unauthorized access is prohibited.' > /etc/issue.net

# Mail queue permissions
if command -v postfix >/dev/null 2>&1; then
	chmod 700 /var/spool/postfix/maildrop 2>/dev/null || true
fi

HARDN_STATUS "pass" "Lynis score improvements applied successfully."
