name: Build Debian Package

on:
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper fakeroot

      - name: Build Debian package
        run: |
          dpkg-buildpackage -us -uc

      - name: Archive Debian package
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: ../*.deb
